spring:
  config:
    activate:
      on-profile: local
---
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092, localhost:9093, localhost:9094
  config:
    activate:
      on-profile: local

---
spring:
  kafka:
    producer:
      bootstrap-servers: dev:9092, dev:9093, dev:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  config:
    activate:
      on-profile: dev
---
spring:
  kafka:
    producer:
      bootstrap-servers: prod:9092, prod:9093, prod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  config:
    activate:
      on-profile: prod